import React from 'react'
import { storiesOf } from '@storybook/react'
import { action } from '@storybook/addon-actions'

import Button from '../src/components/Button/Button'

storiesOf('Buttons', module)
  .add('Small Size', () => (
    <div>
      <Button
        onClick={action('clicked')}
        buttonType={'primary'}
        buttonSize={'sm'}
        label={'primary'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'secondary'}
        buttonSize={'sm'}
        label={'secondary'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'success'}
        buttonSize={'sm'}
        label={'success'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'info'}
        buttonSize={'sm'}
        label={'info'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'warning'}
        buttonSize={'sm'}
        label={'warning'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'danger'}
        buttonSize={'sm'}
        label={'danger'}
      />
    </div>
  ))
  .add('Medium Size', () => (
    <div>
      <Button
        onClick={action('clicked')}
        buttonType={'primary'}
        buttonSize={'md'}
        label={'primary'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'secondary'}
        buttonSize={'md'}
        label={'secondary'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'success'}
        buttonSize={'md'}
        label={'success'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'info'}
        buttonSize={'md'}
        label={'info'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'warning'}
        buttonSize={'md'}
        label={'warning'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'danger'}
        buttonSize={'md'}
        label={'danger'}
      />
    </div>
  ))
  .add('Large Size', () => (
    <div>
      <Button
        onClick={action('clicked')}
        buttonType={'primary'}
        buttonSize={'lg'}
        label={'primary'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'secondary'}
        buttonSize={'lg'}
        label={'secondary'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'success'}
        buttonSize={'lg'}
        label={'success'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'info'}
        buttonSize={'lg'}
        label={'info'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'warning'}
        buttonSize={'lg'}
        label={'warning'}
      />
      <Button
        onClick={action('clicked')}
        buttonType={'danger'}
        buttonSize={'lg'}
        label={'danger'}
      />
    </div>
  ))
